FROM ubi8/ubi:8.5
MAINTAINER Diego Villegas dvillegast3@gmail.com
LABEL description="A custom Apache container based on UBI 8"
RUN yum install -y httpd && \
    yum clean all
RUN echo "Diego Villegas nuevo" > /var/www/html/index.html
EXPOSE 8080
RUN chown 48:48 /etc/httpd/logs \
    chown 48:48 /run/httpd
ENV PORT "8080"

CMD ["httpd", "-D", "FOREGROUND"]


